baseURL = "https://bgronas.github.io/nutanix/" 
languageCode = "en-us"
title = "Nutanix Dump"
theme = "hugo-clarity"
publishDir = "docs"           # VIKTIG: GitHub Pages leser fra denne mappen
enableRobotsTXT = true
canonifyURLs = true           # Hjelper med å fikse stier på Project Pages

[params]
  author = "Bengt Grønås"
  email = "mail@bengt.no"
  description = "Nutanix Technical Dives"
  
  # Layout
  usePageBundles = true
  mainSections = ["post"]
  dateFormat = "2006-01-02"
  
  # "Nutanix Dark Mode" look
  enforceDarkMode = true 
  custom_background_color = "#0b0b0b" 
  custom_font_color = "#e0e0e0"
  
  logo = "img/nutanix_logo.png"
  mobileNavigation = "left"

  # Code blocks
  codeMaxLines = 20
  codeLineNumbers = true

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1