# VIKTIG: BaseURL må matche repo-navnet ditt nøyaktig
baseURL = "https://bgronas.github.io/nutanix/" 
languageCode = "en-us"
title = "My Secret Dump"
theme = "hugo-clarity"
publishDir = "docs" # Sender generert HTML til docs-mappen
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Bengt Grønås"
  email = "mail@bengt.no"
  description = "Nutanix Technical Deep Dives"
  
  # Windows & Layout innstillinger
  usePageBundles = true
  mainSections = ["post"]
  dateFormat = "2006-01-02"
  
  # Dark Mode for "Hacker" feel
  enforceDarkMode = true 
  custom_background_color = "#0b0b0b" 
  custom_font_color = "#e0e0e0"
  
  logo = "img/nutanix_logo.png"
  mobileNavigation = "left"

  # Kodeblokker
  codeMaxLines = 20
  codeLineNumbers = true

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1